---
version: "2"
services:
  slskd:
    user: "1000:1000"
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_SHARED_DIR=/srv/slskd/app/downloads
    volumes:
      - ./app:/app
    restart: unless-stopped