# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = { 
      device = "/dev/disk/by-uuid/2c1aa9ba-ada3-46f8-bb1d-0471c5af2ec9";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

    "/nix" = { 
      device = "/dev/disk/by-uuid/2c1aa9ba-ada3-46f8-bb1d-0471c5af2ec9";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

    "/persist" = { 
      device = "/dev/disk/by-uuid/2c1aa9ba-ada3-46f8-bb1d-0471c5af2ec9";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

    "/var/log" = { 
      device = "/dev/disk/by-uuid/2c1aa9ba-ada3-46f8-bb1d-0471c5af2ec9";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };
  
    "/boot" = {
      device = "/dev/disk/by-uuid/B023-7AC4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  
    "/mnt/storage" = {
      device = "/dev/disk/by-uuid/86d45fb5-9f89-4867-aac5-4e99a1669c35";
      fsType = "ext4";
      options = [ "nofail" "rw" "user" "exec" ];
    };
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/668289c5-8b91-4c2d-acd0-36812b71461e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
