from .data import (APP_NAME, APP_NAME_CAP, NOTIF_POS_DEFAULT, NOTIF_POS_KEY,
                   PANEL_POSITION_DEFAULT, PANEL_POSITION_KEY,
                   WALLPAPERS_DIR_DEFAULT)

SOURCE_STRING = f"""
# {APP_NAME_CAP}
source = ~/.config/{APP_NAME_CAP}/config/hypr/{APP_NAME}.conf
"""

DEFAULTS = {
    'prefix_restart': "SUPER ALT",
    'suffix_restart': "B",
    'prefix_axmsg': "SUPER",
    'suffix_axmsg': "A",
    'prefix_dash': "SUPER",
    'suffix_dash': "D",
    'prefix_bluetooth': "SUPER",
    'suffix_bluetooth': "B",
    'prefix_pins': "SUPER",
    'suffix_pins': "Q",
    'prefix_kanban': "SUPER",
    'suffix_kanban': "N",
    'prefix_launcher': "SUPER",
    'suffix_launcher': "R",
    'prefix_tmux': "SUPER",
    'suffix_tmux': "T",
    'prefix_cliphist': "SUPER",
    'suffix_cliphist': "V",
    'prefix_toolbox': "SUPER",
    'suffix_toolbox': "S",
    'prefix_overview': "SUPER",
    'suffix_overview': "TAB",
    'prefix_wallpapers': "SUPER",
    'suffix_wallpapers': "COMMA",
    'prefix_randwall': "SUPER SHIFT",
    'suffix_randwall': "COMMA",
    'prefix_emoji': "SUPER",
    'suffix_emoji': "PERIOD",
    'prefix_power': "SUPER",
    'suffix_power': "ESCAPE",
    'prefix_caffeine': "SUPER SHIFT",
    'suffix_caffeine': "M",
    'prefix_toggle': "SUPER CTRL",
    'suffix_toggle': "B",
    'prefix_css': "SUPER SHIFT",
    'suffix_css': "B",
    'wallpapers_dir': WALLPAPERS_DIR_DEFAULT,
    'prefix_restart_inspector': "SUPER CTRL ALT",
    'suffix_restart_inspector': "B",
    'bar_position': "Top",  # New default position setting
    'vertical': False,  # Kept for backward compatibility
    'centered_bar': False,
    'terminal_command': "kitty -e",
    'dock_enabled': True,
    'dock_icon_size': 28,
    'dock_always_occluded': False,
    'bar_workspace_show_number': False,
    'bar_workspace_use_chinese_numerals': False,
    'bar_theme': "Pills",
    'dock_theme': "Pills",
    'panel_theme': "Notch", # Default panel theme
    PANEL_POSITION_KEY: PANEL_POSITION_DEFAULT, # Default panel position
    NOTIF_POS_KEY: NOTIF_POS_DEFAULT, # Nueva entrada para la posición de notificaciones
    'bar_button_apps_visible': True,
    'bar_systray_visible': True,
    'bar_control_visible': True,
    'bar_network_visible': True,
    'bar_button_tools_visible': True,
    'bar_button_overview_visible': True,
    'bar_ws_container_visible': True,
    'bar_weather_visible': True,
    'bar_battery_visible': True,
    'bar_metrics_visible': True,
    'bar_language_visible': True,
    'bar_date_time_visible': True,
    'bar_button_power_visible': True,
    'corners_visible': True,
    'bar_metrics_disks': ["/"],
    'metrics_visible': {
        'cpu': True,
        'ram': True,
        'disk': True,
        'gpu': True,
    },
    'metrics_small_visible': {
        'cpu': True,
        'ram': True,
        'disk': True,
        'gpu': True,
    },
}
