directory: /mnt/storage/music

import:
    move: yes
    copy: no
    write: yes
    autotag: yes
    timid: no
    incremental: yes
    quiet_fallback: asis
paths:
    default: $albumartist/$original_year - $album%aunique{}/$track - $title

match:
    strong_rec_thresh: 0.10

ui:
    color: yes

plugins: musicbrainz fromfilename fetchart lastgenre lyrics


lastgenre:
    source: album
    count: 6
    canonical: /var/lib/beets/.config/beets/genres.yaml
    whitelist: /var/lib/beets/.config/beets/whitelist.txt
    force: yes
    keep_existing: no
    auto: yes

lyrics:
    force: no
    fallback: ''
    sources: lrclib
    synced: yes