[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [
    "img", "-t", "outer",
    "--transition-duration", "1.5",
    "--transition-step", "255",
    "--transition-fps", "60",
    "-f", "Nearest"
]
set = true

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[templates.hyprland]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/matugen/config/hypr/colors.conf"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/matugen/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"