[preset 1]
legacy_layout=false
hud_compact
horizontal
position=bottom-center
offset_y=8
background_alpha=0.4
font_size=12
font_size_secondary=12
text_color=E6E6E6
fps_limit_method=late

time
time_format=%I:%M %p

custom_text=

gpu_stats
gpu_temp
gpu_core_clock
gpu_power
gpu_color=E05A5A

exec=cat /sys/class/drm/card1/device/power_dpm_force_performance_level 

vram
gpu_mem_clock
proc_vram
vram_color=B48EED

custom_text=

cpu_stats
cpu_temp
cpu_mhz
cpu_power
cpu_color=6FCF97

exec=cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

ram
ram_color=F2A65A
procmem

custom_text=

fps
engine_short_names
frametime
frame_timing

show_fps_limit

winesync
display_server
wine
wine_color=E6E6E6

throttling_status



[preset 2]
legacy_layout=false
hud_compact
horizontal
position=bottom-center
offset_y=8
background_alpha=0.4
font_size=12
font_size_secondary=12
text_color=E6E6E6
fps_limit_method=late

time
time_format=%I:%M %p

custom_text=

gpu_stats
gpu_temp
gpu_core_clock
gpu_power
gpu_color=E05A5A

exec=cat /sys/class/drm/card1/device/power_dpm_force_performance_level 

vram
gpu_mem_clock
vram_color=B48EED

custom_text=

cpu_stats
cpu_temp
cpu_mhz
cpu_power
cpu_color=6FCF97

exec=cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

ram
ram_color=F2A65A

fps
engine_short_names
frametime
frame_timing

show_fps_limit

winesync
display_server
wine
wine_color=E6E6E6

throttling_status



[preset 3]
legacy_layout=false
hud_compact
horizontal
position=bottom-center
offset_y=8
background_alpha=0.4
font_size=12
font_size_secondary=12
text_color=E6E6E6
fps_limit_method=late

time
time_format=%I:%M %p

gpu_stats
gpu_temp
gpu_color=E05A5A

vram
vram_color=B48EED

cpu_stats
cpu_temp
cpu_color=6FCF97

ram
ram_color=F2A65A

fps
frametime
frame_timing



[preset 4]
legacy_layout=false
hud_compact
horizontal
position=bottom-center
offset_y=8
background_alpha=0
font_size=12
font_size_secondary=12
text_color=E6E6E6
fps_limit_method=late

time
time_format=%I:%M %p

fps